workflows:
  privacy-cash-ios:
    name: PrivacyCash iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Install dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install
      - name: Build web assets
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build
      - name: Sync Capacitor iOS
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..
      - name: Build iOS App
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -derivedDataPath build
          cd ../..
    artifacts:
      - ios/App/build/**/*.app
    publishing:
      email:
        recipients:
          - peenascimento52@gmail.com
        notify:
          success: true
          failure: true

  privacy-cash-android:
    name: PrivacyCash Android Build
    instance_type: linux
    max_build_duration: 120
    environment:
      node: latest
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Install dependencies
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install
      - name: Build web assets
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build
      - name: Sync Capacitor Android
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleRelease
          cd ..
    artifacts:
      - android/app/build/outputs/apk/release/**/*.apk
    publishing:
      email:
        recipients:
          - peenascimento52@gmail.com
        notify:
          success: true
          failure: true