workflows:
  privacy-cash-ios:
    name: PrivacyCash iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.privacycash.app"
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      node: latest
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
          cd ../..

      - name: Build iOS App Archive
        script: |
          xcodebuild build-for-testing \
            -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build

      - name: Create IPA
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            -destination generic/platform=iOS \
            archive -archivePath build/PrivacyCash.xcarchive && \
          xcodebuild -exportArchive \
            -archivePath build/PrivacyCash.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/**/*.ipa

    publishing:
      email:
        recipients:
          - peenascimento52@gmail.com
        notify:
          success: true
          failure: true
